In [167]:
import numpy as np 
import numpy.linalg as linal
import matplotlib.pyplot as plt

## Fast Fourier Transform 
* Decimation in time 
$$ X[k] = E[k] + W_{N}^{k}\cdot O[k]

In [2]:
def W(N) :
    return np.exp(-1.0j*2*np.pi/N)

In [152]:
# Works for any one dimensional array as input but will not work for 2d arrays
# Make sure that the input is one dimensional before passing 

def dit(x,k):
    
    N = len(x)
    
    if N == 1:
        return x
    else:
        X_even = dit(x[::2],k)
        X_odd = dit(x[1::2],k)
        factor = np.exp(-2j*np.pi*k/N)
        
        return X_even + X_odd*factor

In [189]:
def dit2(x):
    
    N = len(x)
    
    if N == 1:
        return x
    else:
        E = dit2(x[::2])
        O = dit2(x[1::2])
        factor = np.exp(-2j*np.pi*np.arange(N)/N)

         
        X = np.concatenate([E+factor[:int(N/2)]*O, E+factor[int(N/2):]*O])
        
        return X

In [155]:
fft_coeffs = np.empty((N,1), dtype=complex)
for i in range(N) :
   fft_coeffs[i] = dit(time_signal,i)

In [156]:
fft_coeffs

array([[36.+0.j        ],
       [-4.+9.65685425j],
       [-4.+4.j        ],
       [-4.+1.65685425j],
       [-4.-0.j        ],
       [-4.-1.65685425j],
       [-4.-4.j        ],
       [-4.-9.65685425j]])

In [190]:
dit2(time[0])

array([36.+0.j        , -4.+9.65685425j, -4.+4.j        , -4.+1.65685425j,
       -4.-0.j        , -4.-1.65685425j, -4.-4.j        , -4.-9.65685425j])

### Input the number of samples to Evaluate the DFT

In [4]:
# x[k] = time sample at t = kT/N
N = int(input ("Enter the number of Coefficient you would like to calculate [use N of the form 2^p] : "))

### DFT Matrix Computation

In [52]:
DFT = np.empty((N,N),dtype=complex)

for i in range(0,N) :  
    for j in range(0,N) : 
        DFT[i,j] = W(N)**(i*j)

### Enter the values of the time singal 

In [17]:
time_signal = np.empty((N,1))
for i in range(N) : 
    value = float(input(f"Enter the time signal evaluated at {i}/{N}*T : "))
    time_signal[i] = value


### Fourier Coefficients Calculation :

In [53]:
Fourier_coeffs = DFT@time_signal
Fourier_coeffs

array([[36.+0.j        ],
       [-4.+9.65685425j],
       [-4.+4.j        ],
       [-4.+1.65685425j],
       [-4.-0.j        ],
       [-4.-1.65685425j],
       [-4.-4.j        ],
       [-4.-9.65685425j]])